<!DOCTYPE html>
<html>
<head>
<title>Olapic App Mediator</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3.css">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/olapic.css">
</head>
<body class="w3-light-grey">
    <header class="w3-container w3-teal w3-center">
        <h2>Olapic App</h2>
    </header>
    <!-- Page Container -->
    <div class="w3-content w3-margin-top" style="max-width:1400px;">
        <?php
        if(! empty( $result ) ) {
            ?>
            <!-- The Grid -->
            <div class="w3-row-padding">
                <!-- Left Column -->
                <div class="w3-third">
                    <div class="w3-white w3-text-grey w3-card-4">
                        <div class="w3-container">
                            <h2>Customer Info</h2>
                            <!--                        <input oninput="w3.filterHTML('#customers', 'li', this.value)" placeholder="Search for names..">-->
                            ID: <span id="customer_id"><?php echo $result['customer']['id'] ?></span><br/>
                            Name: <?php echo $result['customer']['name']; ?><br/>
                            Language: <?php echo $result['customer']['language'] ?><br/>
                           <!-- <a href="https:<?php echo $result['customer']['_embedded']['user']['_links']['self']['href']; ?>">View User Information</a>-->
                            <hr/>
                            <ul id="media_links" class="w3-ul w3-hoverable">
                                Click Links Below To View Images:
                                <li media-type="recent" customer-id="<?php echo $result['customer']['id']; ?>">View
                                    Media
                                </li>
                                <li media-type="recent" customer-id="<?php echo $result['customer']['id']; ?>">View
                                    Recent Media
                                </li>
                                <li media-type="shuffled" customer-id="<?php echo $result['customer']['id']; ?>">View
                                    Shuffled Media
                                </li>
                                <li media-type="photorank" customer-id="<?php echo $result['customer']['id']; ?>">View
                                    Photo Ranked Media
                                </li>
                                <li media-type="rated" customer-id="<?php echo $result['customer']['id']; ?>">View Rated
                                    Media
                                </li>
                            </ul>
                        </div>
                    </div>
                    <br/>
                    <!-- End Left Column -->
                </div>
                <!-- Right Column -->
                <div class="w3-twothird">
                    <div class="w3-container w3-card-2 w3-white">
                        <h2 class="w3-text-grey w3-padding-16" id="images_header">Customer Images will show below</h2>

                        <div class="w3-container" id="images">
                        </div>
                    </div>

                    <!-- End Right Column -->
                </div>
                <!-- End Grid -->
            </div>
            <?php
        }else{
            echo '<h1>There was an issue loading the app. Please try again later.</h1>';
                if( !empty( $error ) ){
                   echo '<p>Error: '.$error.'</p>';
                }
        }
        ?>
        <!-- End Page Container -->
    </div>
    <footer class="w3-container w3-teal w3-center w3-margin-top">
        <p>Developed by Darwin Salgado &copy; 2017</p>
        <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
    </footer>
    </body>
</html>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://frontend-lab.s3.amazonaws.com/pi-test-console/sdk.min.js"></script>
<script src="scripts/customers.js"></script>
